"""Python export: bundle a runnable script that reproduces the strategy.

The exporter takes a validated StrategySchema, stamps the JSON into a static
template (templates/strategy_template.py), and bundles it with a
requirements.txt and README.md. The output is a 100% self-contained Python
project — `pip install -r requirements.txt && python strategy.py` reproduces
the headline metrics without any StratLab dependency.

Why a static template instead of a code generator: it's much easier to
maintain (you can run the template file directly during development), and
inlining all 18 indicators is cheap (~200 LOC of Python). The only thing
that varies per export is the JSON spec.
"""

from __future__ import annotations

from importlib import resources
from pathlib import Path

from pydantic import BaseModel
from stratlab_schema import StrategySchema

PLACEHOLDER_JSON = "__SCHEMA_JSON__"
PLACEHOLDER_NAME = "__STRATEGY_NAME__"

# Pin versions to known-good as of this commit so a 2030 export still installs.
REQUIREMENTS_TXT = """\
ccxt==4.4.41
numpy>=1.26
pandas>=2.1
"""


class ExportBundle(BaseModel):
    """The set of files we hand back as a downloadable bundle."""

    strategy_py: str
    requirements_txt: str
    readme_md: str
    files: dict[str, str]   # filename → contents (mirror of the above for tabs)


def build_export_bundle(schema: StrategySchema) -> ExportBundle:
    template = _load_template()
    schema_json = schema.model_dump_json(indent=2)
    safe_name = schema.name.replace('"""', '\\"\\"\\"')
    strategy_py = template.replace(PLACEHOLDER_JSON, schema_json).replace(
        PLACEHOLDER_NAME, safe_name
    )
    readme = _readme_for(schema)
    return ExportBundle(
        strategy_py=strategy_py,
        requirements_txt=REQUIREMENTS_TXT,
        readme_md=readme,
        files={
            "strategy.py": strategy_py,
            "requirements.txt": REQUIREMENTS_TXT,
            "README.md": readme,
        },
    )


def _load_template() -> str:
    # Use importlib.resources so this works once installed as a wheel.
    pkg = resources.files("stratlab_api.exporters.templates")
    path = pkg / "strategy_template.py"
    return Path(str(path)).read_text(encoding="utf-8")


def _readme_for(schema: StrategySchema) -> str:
    asset = schema.data.asset.value
    tf = schema.data.timeframe.value
    start = schema.data.start.isoformat()
    end = schema.data.end.isoformat()
    return f"""\
# {schema.name}

Generated by StratLab — a conversational quant research workbench.

This is a fully self-contained Python script. It does **not** depend on the
StratLab platform itself; it only needs `ccxt`, `numpy`, and `pandas`.

## What it does

- Loads {asset} {tf} OHLCV from Binance public REST (via ccxt)
  for the window {start} → {end}
- Computes the indicators referenced by your strategy
- Runs a simplified long-only bar-loop backtester (fixed-fraction sizing,
  fees + slippage, intra-bar stops & take-profits)
- Prints headline metrics (Sharpe, total return, max drawdown, trades, win rate)

## Run

```bash
pip install -r requirements.txt
python strategy.py
```

## What's NOT in this export

The StratLab dashboard ships three anti-overfit views that are **not**
reproduced here:

- **Sensitivity halo** — perturbs each parameter ±20% and renders the
  envelope of the resulting equity curves
- **Regime decomposition** — Sharpe per (low-vol / high-vol) and
  (trending / sideways) regime
- **Cost stress** — the same backtest at 1.5× and 2× the assumed fees

Open the strategy in the StratLab workbench to see them.

## The spec

The `STRATEGY` dict at the top of `strategy.py` is the same Pydantic-validated
JSON the StratLab engine consumed. Edit values in place and re-run to iterate.

> Tip: try widening the entry threshold or tightening the stop, then compare
> the resulting Sharpe to the StratLab dashboard's number to make sure your
> intuition matches the engine's.
"""
